pipeline:
  build:
    image: node:8.9-alpine
    commands:
      - npm install

  publish:
    image: plugins/docker
    repo: aafrey/drone-elastic-test
    tags:
      - latest
      - 0.0.2-${DRONE_COMMIT_SHA:0:7}
    environment:
      - ELASTIC_URL=${ELASTIC_URL}
    secrets:
      - docker_username
      - docker_password
      - elastic_url

  rancher:
    image: peloton/drone-rancher
    url: http://admin.zi.gy
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: ELK/tweet-cache
    docker_image: aafrey/drone-elastic-test:0.0.2-${DRONE_COMMIT_SHA:0:7}
    secrets: [ rancher_access_key, rancher_secret_key ]
